version: "3.2"
services:
  api:
    env_file:
      - docker_env
    build:
      context: ./
      dockerfile: DockerfileAPI
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
