# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: devdb
        ports:
          - 5432:5432

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Actions
      - name: Echo GITHUB_WORSPACE
        run: echo $GITHUB_WORKSPACE

      - name: Export PATH
        run: export PATH="$GITHUB_WORKSPACE/split_expenses_api:$PATH"

      - name: Backend unit tests checks
        run: pip install -r test-requirements.txt && pytest .
        env:
          DB_HOST: postgres

      - name: Backend linting checks
        run: pip install flake8==3.9 && flake8 $GITHUB_WORKSPACE/split_expenses_api

      # - name: Frontend unit tests checks
      #   run: cd $GITHUB_WORKSPACE/split_expenses_ui && npm i && npm run test

      # - name: Frontend linting checks
      #   run: cd $GITHUB_WORKSPACE/split_expenses_ui && npm run lint
